#pragma once

#include "controller_interface/controller_interface.hpp"
#include "controller_interface/helpers.hpp"

#include "control_toolbox/pid.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"

#include <unitree_go/msg/motor_cmd.hpp>
#include <unitree_go/msg/motor_state.hpp>
#include <unitree_go/msg/motor_cmds.hpp>
#include <unitree_go/msg/motor_states.hpp>

#include "realtime_tools/realtime_buffer.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_server_goal_handle.hpp"

#include "lifecycle_msgs/msg/state.hpp"

#include "rclcpp/version.h"
#if RCLCPP_VERSION_GTE(29, 0, 0)
#include "urdf/model.hpp"
#else
#include "urdf/model.h"
#endif

// auto-generated by generate_parameter_library
#include "unitree_joint_controller/unitree_joint_controller_parameters.hpp"

using namespace std::chrono_literals;  // NOLINT

#define PMSM (0x01)
#define BRAKE (0x00)
#define PosStopF  (2.146E+9f)
#define VelStopF  (16000.0f)

namespace unitree_joint_controller
{
    class UnitreeJointController : public controller_interface::ControllerInterface
    {
        public:
            UnitreeJointController();
            
            /**
            * @brief command_interface_configuration
            */
            controller_interface::InterfaceConfiguration command_interface_configuration() const override;

            /**
            * @brief command_interface_configuration
            */
            controller_interface::InterfaceConfiguration state_interface_configuration() const override;

            controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;

            controller_interface::CallbackReturn on_init() override;

            rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn on_configure(
                const rclcpp_lifecycle::State & previous_state) override;

            rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn on_activate(
                const rclcpp_lifecycle::State & previous_state) override;

            rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn on_deactivate(
                const rclcpp_lifecycle::State & previous_state) override;

            rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn on_cleanup(
                const rclcpp_lifecycle::State & previous_state) override;

            rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn on_error(
                const rclcpp_lifecycle::State & previous_state) override;

        protected:

            void command_callback(const unitree_go::msg::MotorCmds & msg);

            rclcpp::Duration state_publisher_period_ = rclcpp::Duration(20ms);

            // To reduce number of variables and to make the code shorter the interfaces are ordered in types
            // as the following constants
            const std::vector<std::string> allowed_interface_types_ = {
                hardware_interface::HW_IF_POSITION,
                hardware_interface::HW_IF_VELOCITY,
                hardware_interface::HW_IF_ACCELERATION,
                hardware_interface::HW_IF_EFFORT,
            };        

            // The interfaces are defined as the types in 'allowed_interface_types_' member.
            // For convenience, for each type the interfaces are ordered so that i-th position
            // matches i-th index in joint_names_
            template <typename T>
            using InterfaceReferences = std::vector<std::vector<std::reference_wrapper<T>>>;

            InterfaceReferences<hardware_interface::LoanedCommandInterface> joint_command_interface_;
            InterfaceReferences<hardware_interface::LoanedStateInterface> joint_state_interface_;

            // Degrees of freedom
            size_t dof_ = 0;

            // Storing command joint names for interfaces
            std::vector<std::string> command_joint_names_;

            bool has_position_state_interface_ = false;
            bool has_effort_command_interface_ = false;

            // Parameters from ROS for joint_trajectory_controller
            std::shared_ptr<unitree_joint_controller::ParamListener> param_listener_;
            unitree_joint_controller::Params params_;

            rclcpp::Subscription<unitree_go::msg::MotorCmds>::SharedPtr joint_command_subscriber_ =
                nullptr;

            using ControllerStateMsg = unitree_go::msg::MotorStates;
            using StatePublisher = realtime_tools::RealtimePublisher<ControllerStateMsg>;
            using StatePublisherPtr = std::unique_ptr<StatePublisher>;
            rclcpp::Publisher<ControllerStateMsg>::SharedPtr publisher_legacy_;
            StatePublisherPtr state_publisher_legacy_;
            rclcpp::Publisher<ControllerStateMsg>::SharedPtr publisher_;
            StatePublisherPtr state_publisher_;            

            unitree_go::msg::MotorStates state_current_;
            unitree_go::msg::MotorStates state_tmin1_;
            unitree_go::msg::MotorStates state_tmin2_;

            unitree_go::msg::MotorCmds command_current_;

            realtime_tools::RealtimeBuffer<unitree_go::msg::MotorCmds> command_buffer_;

        private:

            void clampInPlaceCustom(float & rawValue, const float & minValue, const float & maxValue, 
                                    const std::string & joint_name = "", const std::string & limit_type = "")
            {
                // if (rawValue < minValue || rawValue > maxValue)
                // {
                //     RCLCPP_WARN_STREAM(
                //         get_node()->get_logger(),
                //         "Clamping " << limit_type << " of joint '" << joint_name << "' from " << rawValue
                //                     << " to range [" << minValue << ", " << maxValue << "]");
                // }
                float clampedVel = std::max(minValue, std::min(rawValue, maxValue));
                rawValue = clampedVel;
                // eg. clamp(1.5, -1, 1) = 1
                return;
            }

            float computeVel(const float & current_position, const float & last_position, 
                                const float & last_velocity, const float & duration)
            {
                // std::cerr << "computeVel called with current_position: " << current_position
                //           << ", last_position: " << last_position
                //           << ", last_velocity: " << last_velocity
                //           << ", duration: " << duration << std::endl;
                // eg. computeVel(1.5, 1.0, 0.5, 0.01) = 50
                if (duration <= 0.0)
                    return last_velocity;

                float vel = (current_position - last_position) / duration;

                // std::cerr << "Computed velocity: " << vel << std::endl;
                
                return vel;
            }

            float computeTorqueCustom(const float & current_position, const float & current_velocity, const unitree_go::msg::MotorCmd & cmd)  // get torque 
            {
                return cmd.tau + cmd.kp*(cmd.q - current_position) + cmd.kd*(cmd.dq - current_velocity);
            } 

            void positionLimits(const std::string & joint_name, float &position);
            void velocityLimits(const std::string & joint_name, float &velocity);
            void effortLimits(const std::string & joint_name, float &effort);

            bool read_state_from_state_interfaces(unitree_go::msg::MotorStates & state);

            // void update_pids();

            bool contains_interface_type(
                const std::vector<std::string> & interface_type_list, const std::string & interface_type);

            // Reset function to reset the controller
            bool reset();

            // bool use_closed_loop_pid_adapter_ = false;
            // PIDs for each joint
            // using PidPtr = std::shared_ptr<control_toolbox::Pid>;
            // std::vector<PidPtr> pids_;

            // Configuration for every joint if it wraps around (ie. is continuous, position error is
            // normalized)
            // std::vector<bool> joints_angle_wraparound_;
            // reserved storage for result of the command when closed loop pid adapter is used
            // std::vector<float> tmp_command_;  
            
            urdf::Model model_;

            float timeSinceLastLog_ = 1e5;
    };
    
} // namespace unitree_joint_controller
